name: "MB_sudden"
batch_size: 500
shuffle_within_group: false

data:
  mode: files
  text_col: "text"
  label_col: "label"
  sources:
    books: "../data/books_label.csv"
    movies: "../data/movies_and_tv_label.csv"

plan:
  - { group: "movies", batches: 15 }
  - { group: "books", batches: 10 }