name: "EB_sudden"
batch_size: 500
shuffle_within_group: false

data:
  mode: files
  text_col: "text"
  label_col: "label"
  sources:
    books: "../data/books_label.csv"
    electronics: "../data/electronics_label.csv"

plan:
  - { group: "electronics", batches: 15 }
  - { group: "books", batches: 10 }