name: "KB_sudden"
batch_size: 500
shuffle_within_group: false

data:
  mode: files
  text_col: "text"
  label_col: "label"
  sources:
    books: "../data/domain/books_label.csv"
    kitchen: "../data/domain/home_and_kitchen_label.csv"

plan:
  - { group: "kitchen", batches: 15 }
  - { group: "books", batches: 10 }