name: "KM_sudden"
batch_size: 500
shuffle_within_group: false

data:
  mode: files
  text_col: "text"
  label_col: "label"
  sources:
    movies: "../data/domain/movies_and_tv_label.csv"
    kitchen: "../data/domain/home_and_kitchen_label.csv"

plan:
  - { group: "kitchen", batches: 15 }
  - { group: "movies", batches: 10 }