name: "cfpb_company_sudden"
batch_size: 500
shuffle_within_group: false
seed: 42

data:
  mode: files
  text_col: "text"
  label_col: "label"
  sources:
    A: "../data/cfpb/cfpb_company_topN.csv"
    B: "../data/cfpb/cfpb_company_other.csv"

plan:
  - { group: "A", batches: 20 }
  - { group: "B", batches: 25 }
